"""fix post image cascade delete

Revision ID: eebccbade70f
Revises: f99aab5c26c2
Create Date: 2026-06-02 19:24:44.737713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'eebccbade70f'
down_revision: Union[str, Sequence[str], None] = 'f99aab5c26c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('post_images_post_uid_fkey'), 'post_images', type_='foreignkey')
    op.create_foreign_key(None, 'post_images', 'posts', ['post_uid'], ['uid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_images', type_='foreignkey')
    op.create_foreign_key(op.f('post_images_post_uid_fkey'), 'post_images', 'posts', ['post_uid'], ['uid'])
    # ### end Alembic commands ###
